package harness

import (
	"context"
	"database/sql"
	"errors"
	"fmt"
	"time"
)

// bg is the context for all seeding operations.
func bg() context.Context { return context.Background() }

// ErrBackendUnavailable reports that an external database (e.g. the
// postgres container from bench/dockerfile) is not reachable. Runners
// turn it into a visible skip so local runs stay green without docker.
var ErrBackendUnavailable = errors.New("database backend unavailable")

// seedShopStmts returns deterministic fixture DDL+DML per backend.
func seedShopStmts(backend string) []string {
	if backend == "postgres" {
		return []string{
			`CREATE TABLE users (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				full_name TEXT NOT NULL,
				email TEXT NOT NULL UNIQUE,
				age INTEGER,
				active BOOLEAN NOT NULL DEFAULT TRUE,
				bio TEXT,
				created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE TABLE products (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				name TEXT NOT NULL,
				price DOUBLE PRECISION NOT NULL,
				users_id INTEGER REFERENCES users(id)
			)`,
			`CREATE TABLE orders (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				user_id INTEGER REFERENCES users(id),
				total DOUBLE PRECISION NOT NULL,
				status TEXT NOT NULL,
				created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
			)`,
			`CREATE TABLE items (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				order_id INTEGER REFERENCES orders(id),
				product_id INTEGER REFERENCES products(id),
				qty INTEGER NOT NULL
			)`,
			`CREATE TABLE tags (
				id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
				label TEXT NOT NULL UNIQUE
			)`,
			`CREATE TABLE product_tags (
				product_id INTEGER REFERENCES products(id),
				tag_id INTEGER REFERENCES tags(id),
				UNIQUE(product_id, tag_id)
			)`,
			`INSERT INTO users (id, full_name, email, age, active, bio) VALUES
				(1, 'Ada Lovelace', 'ada@example.com', 36, TRUE, 'first programmer'),
				(2, 'Alan Turing', 'alan@example.com', 41, TRUE, NULL),
				(3, 'Grace Hopper', 'grace@example.com', 85, FALSE, 'COBOL whisperer')`,
			`INSERT INTO products (id, name, price, users_id) VALUES
				(1, 'Analytical Engine', 999.99, 1),
				(2, 'Enigma Replica', 499.50, 2),
				(3, 'Compiler Design', 149.00, 3),
				(4, 'COBOL Manual', 39.99, 3)`,
			`INSERT INTO orders (id, user_id, total, status, created_at) VALUES
				(1, 1, 1049.49, 'paid',    '2026-01-01T10:00:00Z'),
				(2, 1, 39.99,   'pending', '2026-01-02T11:00:00Z'),
				(3, 2, 499.50,  'shipped', '2026-01-03T12:00:00Z')`,
			`INSERT INTO items (id, order_id, product_id, qty) VALUES
				(1, 1, 1, 1), (2, 1, 3, 2), (3, 2, 4, 1), (4, 3, 2, 1)`,
			`INSERT INTO tags (id, label) VALUES (1,'vintage'), (2,'computing'), (3,'classic')`,
			`INSERT INTO product_tags (product_id, tag_id) VALUES (1,1),(1,2),(2,2),(3,3)`,
			`SELECT setval(pg_get_serial_sequence('users','id'), (SELECT MAX(id) FROM users))`,
			`SELECT setval(pg_get_serial_sequence('products','id'), (SELECT MAX(id) FROM products))`,
			`SELECT setval(pg_get_serial_sequence('orders','id'), (SELECT MAX(id) FROM orders))`,
			`SELECT setval(pg_get_serial_sequence('items','id'), (SELECT MAX(id) FROM items))`,
			`SELECT setval(pg_get_serial_sequence('tags','id'), (SELECT MAX(id) FROM tags))`,
		}
	}
	return []string{
		`CREATE TABLE IF NOT EXISTS users (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			full_name TEXT NOT NULL,
			email TEXT NOT NULL UNIQUE,
			age INTEGER,
			active BOOLEAN NOT NULL DEFAULT 1,
			bio TEXT,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE TABLE IF NOT EXISTS products (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			name TEXT NOT NULL,
			price REAL NOT NULL,
			users_id INTEGER REFERENCES users(id)
		)`,
		`CREATE TABLE IF NOT EXISTS orders (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			user_id INTEGER REFERENCES users(id),
			total REAL NOT NULL,
			status TEXT NOT NULL,
			created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
		)`,
		`CREATE TABLE IF NOT EXISTS items (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			order_id INTEGER REFERENCES orders(id),
			product_id INTEGER REFERENCES products(id),
			qty INTEGER NOT NULL
		)`,
		`CREATE TABLE IF NOT EXISTS tags (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			label TEXT NOT NULL UNIQUE
		)`,
		`CREATE TABLE IF NOT EXISTS product_tags (
			product_id INTEGER REFERENCES products(id),
			tag_id INTEGER REFERENCES tags(id),
			UNIQUE(product_id, tag_id)
		)`,
		`INSERT INTO users (id, full_name, email, age, active, bio) VALUES
			(1, 'Ada Lovelace', 'ada@example.com', 36, 1, 'first programmer'),
			(2, 'Alan Turing', 'alan@example.com', 41, 1, NULL),
			(3, 'Grace Hopper', 'grace@example.com', 85, 0, 'COBOL whisperer')`,
		`INSERT INTO products (id, name, price, users_id) VALUES
			(1, 'Analytical Engine', 999.99, 1),
			(2, 'Enigma Replica', 499.50, 2),
			(3, 'Compiler Design', 149.00, 3),
			(4, 'COBOL Manual', 39.99, 3)`,
		`INSERT INTO orders (id, user_id, total, status, created_at) VALUES
			(1, 1, 1049.49, 'paid',    '2026-01-01T10:00:00Z'),
			(2, 1, 39.99,   'pending', '2026-01-02T11:00:00Z'),
			(3, 2, 499.50,  'shipped', '2026-01-03T12:00:00Z')`,
		`INSERT INTO items (id, order_id, product_id, qty) VALUES
			(1, 1, 1, 1), (2, 1, 3, 2), (3, 2, 4, 1), (4, 3, 2, 1)`,
		`INSERT INTO tags (id, label) VALUES (1,'vintage'), (2,'computing'), (3,'classic')`,
		`INSERT INTO product_tags (product_id, tag_id) VALUES (1,1),(1,2),(2,2),(3,3)`,
	}
}

// ErrBackendUnavailable marker above; SeedShop executes the statements.

// SeedShop creates the full fixture domain with deterministic rows.
//
// Ground truth (scenarios assert against these exact values):
//
//	users:    1=Ada Lovelace  2=Alan Turing  3=Grace Hopper
//	products: 1 Analytical Engine 999.99 (ada)   2 Enigma Replica 499.50 (alan)
//	          3 Compiler Design  149.00 (grace) 4 COBOL Manual 39.99 (grace)
//	orders:   1 ada paid 1049.49   2 ada pending 39.99   3 alan shipped 499.50
//	items:    order1 <- (p1 x2, p3 x1)   order2 <- (p4 x1)   order3 <- (p2 x1)
//	tags:     1 vintage 2 computing 3 classic
//	product_tags: p1<-{vintage,computing} p2<-{computing} p3<-{classic}
//
// Historical assertions (three users, four products, price sum 1688.48,
// ada owns exactly one product) must keep holding.
func SeedShop(db *sql.DB, backend string) error {
	for _, stmt := range seedShopStmts(backend) {
		if _, err := db.ExecContext(bg(), stmt); err != nil {
			return fmt.Errorf("seed shop(%s): %w\nstmt: %s", backend, err, stmt)
		}
	}
	return nil
}

// SeedBlob stores a single ~size-byte text row.
func SeedBlob(db *sql.DB, size int) error {
	if _, err := db.ExecContext(bg(),
		`CREATE TABLE IF NOT EXISTS blobs (
			id INTEGER PRIMARY KEY AUTOINCREMENT,
			content TEXT NOT NULL
		)`); err != nil {
		return err
	}
	payload := make([]byte, size)
	for i := range payload {
		payload[i] = byte('a' + i%26)
	}
	_, err := db.ExecContext(bg(), `INSERT INTO blobs (content) VALUES (?)`, string(payload))
	return err
}

// SeedChain builds n tables ta, tb, tc… where each carries an FK to its
// predecessor, holding exactly one chained row.
func SeedChain(db *sql.DB, n int) error {
	for i := 0; i < n; i++ {
		cur := ChainTable(i)
		prevCol, fk := "", ""
		if i > 0 {
			prevCol = ", prev_id INTEGER"
			fk = fmt.Sprintf(", FOREIGN KEY (prev_id) REFERENCES %s(id)", ChainTable(i-1))
		}
		ddl := fmt.Sprintf(
			`CREATE TABLE %s (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL%s%s)`,
			cur, prevCol, fk,
		)
		if _, err := db.ExecContext(bg(), ddl); err != nil {
			return fmt.Errorf("create %s: %w", cur, err)
		}
		insert := fmt.Sprintf(`INSERT INTO %s (name%s) VALUES ('%s row'`, cur, prevColName(i), cur)
		if i > 0 {
			insert += ", 1"
		}
		insert += ")"
		if _, err := db.ExecContext(bg(), insert); err != nil {
			return fmt.Errorf("seed %s: %w", cur, err)
		}
	}
	return nil
}

func prevColName(i int) string {
	if i > 0 {
		return ", prev_id"
	}
	return ""
}

var _ = time.Second // reserved for future timing-aware seeds

// chainLetters are level names ta…tz minus "to" (SQL keyword).
var chainLetters = func() []string {
	out := []string{}
	for r := 'a'; r <= 'z'; r++ {
		if r == 'o' {
			continue
		}
		out = append(out, "t"+string(r))
	}
	return out
}()

// ChainTable names level i (0-based). Pure-alpha names pass through
// GraphJin's name normalization untouched.
func ChainTable(i int) string {
	if i < len(chainLetters) {
		return chainLetters[i]
	}
	return fmt.Sprintf("tx%d", i) // beyond 25 levels: numeric fallback
}
